import { ComponentDoc } from "@/lib/types";

export const actionsComponents: ComponentDoc[] = [
  {
    slug: "button",
    name: "Button",
    category: "Actions",
    variants: "Style (Primary/Secondary/Danger) × Size (Small/Medium/Large) × State (Default/Hover/Pressed/Focused/Disabled) — 45 variants",
    purpose: "Primary interactive trigger for user actions — submit, confirm, navigate, initiate a process.",
    whenToUse: "For the main action(s) in a view. Use Primary for the single most important action, Secondary for alternative/less prominent actions, Danger for destructive actions requiring confirmation.",
    whenNotToUse: "For page-to-page navigation (use Link). For toggling a binary state (use Switch). For a single icon-only action (use Icon Button).",
    accessibility: "Renders as a real <button>, not a styled <div>. Keyboard: Tab to focus, Enter/Space to activate. Focus uses semantic/focus-ring (5.31:1 contrast, confirmed on the Accessibility page). Never rely on the Disabled state alone to explain unavailability — pair with visible explanatory text nearby.",
    commonMistakes: "More than one Primary button in the same view (dilutes hierarchy). Not disabling the button during an async action (allows double-submission). Skipping a confirmation step for Danger actions just because the button is red.",
    tokensUsed: ["component/radius/control", "semantic/action/primary", "semantic/action/danger", "semantic/surface/default", "semantic/text/inverse", "semantic/text/primary", "semantic/focus-ring", "opacity/disabled"],
    properties: "Style × Size × State as variants. Label (text). Has Icon (boolean) + Icon (instance-swap).",
  },
  {
    slug: "icon-button",
    name: "Icon Button",
    category: "Actions",
    variants: "Style × Size × State — 45 variants",
    purpose: "Compact, icon-only trigger for a single action — used when space is limited or the icon's meaning is universally understood (close, more options, edit).",
    whenToUse: "Toolbars, table row actions, card corner actions — anywhere a text label would be redundant given context.",
    whenNotToUse: "When the icon's meaning isn't obvious without a label — pair with visible text (use Button) or add a Tooltip.",
    accessibility: "MUST have an accessible name via aria-label, since there is no visible text. This component includes a hidden \"Accessible Label\" layer specifically to document what that aria-label should say per instance — never ship an instance without setting it to something real.",
    commonMistakes: "Leaving the Accessible Label at its generic placeholder instead of describing the actual action. Using an ambiguous icon with no tooltip as a fallback.",
    tokensUsed: ["component/radius/control", "semantic/action/primary", "semantic/action/danger", "semantic/surface/default"],
    properties: "Style × Size × State as variants. Icon (instance-swap). Accessible Label (text, hidden layer, drives aria-label in code).",
  },
  {
    slug: "link",
    name: "Link",
    category: "Actions",
    variants: "Style × Size × State — 45 variants",
    purpose: "Inline or standalone navigational/action text, styled to read as part of the content rather than a standalone control.",
    whenToUse: "Navigating to another page or view, or a lower-emphasis action embedded in body text or a list.",
    whenNotToUse: "For the primary action in a form or flow — use Button. Links carry less visual weight and shouldn't be the only way to complete an important task.",
    accessibility: "Renders as a real <a>, not a <button> or <span>. Always underlined by default — a fixed baseline, not a toggle — so link-vs-plain-text is never conveyed by color alone. This was a deliberate accessibility decision made after an earlier draft included a non-functional underline toggle property.",
    commonMistakes: "Using Link where Button is semantically correct (e.g. a form submit action) — affects both code semantics and user expectation.",
    tokensUsed: ["semantic/text/secondary", "semantic/action/primary", "semantic/action/danger", "color/brand/600", "color/brand/700", "semantic/focus-ring"],
    properties: "Style × Size × State as variants. Label (text). Show trailing icon (boolean) + Trailing Icon (instance-swap).",
  },
  {
    slug: "button-group",
    name: "Button Group",
    category: "Actions",
    variants: "Style × Count (2/3/4) — 9 variants",
    purpose: "A set of related, mutually exclusive actions (often a segmented toggle, like a view switcher) visually connected as one unit.",
    whenToUse: "When 2–4 options represent a single choice or view state (e.g. List/Grid view, Day/Week/Month range).",
    whenNotToUse: "For more than ~4 options — use Select or Tabs instead. For unrelated actions that don't belong together visually.",
    accessibility: "In code, implement as role=\"radiogroup\" with each segment as role=\"radio\" when it represents a single selectable state, not a row of independent buttons.",
    commonMistakes: "Giving each segment its own individual border — creates an ugly double-border seam where segments touch. This component deliberately uses one shared outer border + a colored divider gap instead.",
    tokensUsed: ["component/radius/control", "semantic/border/default", "semantic/surface/default", "semantic/action/primary", "semantic/action/danger"],
    properties: "Style × Count as variants. Segment labels are set via direct instance override, not a formal per-segment property.",
  },
  {
    slug: "split-button",
    name: "Split Button",
    category: "Actions",
    variants: "Style × Size — 9 variants",
    purpose: "Combines one primary default action with an adjacent dropdown for closely related alternative actions (e.g. \"Save\" + a chevron revealing \"Save as draft\" / \"Save and publish\").",
    whenToUse: "When there's one clear default action but a few related variants a user occasionally wants instead.",
    whenNotToUse: "When all options are equally likely to be chosen — use a plain Dropdown Menu or Select instead. Split Button implies a clear default.",
    accessibility: "The main action and the chevron trigger are two independently focusable, independently labeled controls in code (two real <button> elements) — never one button with an ambiguous combined action.",
    commonMistakes: "Treating this as a single button. It is two separate interactive targets sharing one visual container, and must be built and labeled as such.",
    tokensUsed: ["component/radius/control", "semantic/action/primary", "semantic/border/default"],
    properties: "Style × Size as variants. Label (text) for the main action only.",
  },
];
