import { ComponentDoc } from "@/lib/types";

export const feedbackComponents: ComponentDoc[] = [
  {
    slug: "badge",
    name: "Badge",
    category: "Feedback",
    variants: "Style × Size — React: neutral/info/success/warning/error × sm/md/lg (no Primary; Figma has Primary × Small/Medium)",
    purpose: "A small, non-interactive status or category label — communicates state or classification at a glance.",
    whenToUse: "Status indicators (New, Beta, Draft), category tags shown read-only, count indicators.",
    whenNotToUse: "A removable, user-generated label — use Content/Tag. An interactive/clickable element.",
    accessibility: "If it conveys meaning beyond decoration, ensure that meaning is also available as text to screen readers.",
    commonMistakes: "Using Badge where Tag (removable) was actually needed.",
    tokensUsed: [
      "semantic/surface/elevated",
      "semantic/text/primary",
      "--badge-info-text",
      "--badge-success-text",
      "--badge-warning-text → color/warning/800",
      "--badge-error-text",
    ],
    properties: "Style × Size as variants. Label (text). Warning text matches Figma (#8A4F00 via warning/800); Neutral/Info/Success/Error foregrounds are accessibility-safe React divergences.",
  },
  {
    slug: "alert",
    name: "Alert",
    category: "Feedback",
    variants: "Type (Info/Success/Warning/Error) — 4 variants",
    purpose: "A prominent, inline message block communicating status directly within page content (not floating above it).",
    whenToUse: "Persistent, contextual messages tied to the content on the page.",
    whenNotToUse: "Transient, auto-dismissing notifications not tied to page content — use Toast.",
    accessibility: "role=\"alert\" (Error/Warning) or role=\"status\" (Info/Success) so screen readers announce it appropriately.",
    commonMistakes: "Using Alert for something that should auto-dismiss.",
    tokensUsed: ["semantic/feedback/info", "semantic/feedback/success", "semantic/feedback/warning", "semantic/action/danger"],
    properties: "Type as variants. Title (text), Description (text), Show close (boolean).",
  },
  {
    slug: "toast",
    name: "Toast",
    category: "Feedback",
    variants: "Type — 4 variants",
    purpose: "A temporary, floating notification confirming an action or reporting a transient event, typically auto-dismissing after a few seconds.",
    whenToUse: "\"Changes saved,\" \"Item deleted\" (with Undo), connection errors.",
    whenNotToUse: "Persistent, content-related messages — use Alert. Anything requiring a user decision — use Dialog.",
    accessibility: "role=\"status\" and aria-live=\"polite\"; must not steal keyboard focus when it appears.",
    commonMistakes: "Making the auto-dismiss timer too short for the message length.",
    tokensUsed: ["semantic/surface/default", "semantic/feedback/info", "semantic/feedback/success", "semantic/action/primary"],
    properties: "Type as variants. Message (text), Show action (boolean) + Action (text), Show close (boolean).",
  },
  {
    slug: "progress-bar",
    name: "Progress Bar",
    category: "Feedback",
    variants: "Style (Default/Success/Warning/Danger) — 4 variants",
    purpose: "Showing determinate progress toward a known completion point (upload percentage, multi-step completion, quota usage).",
    whenToUse: "Any process where percentage-complete is knowable and meaningful.",
    whenNotToUse: "Indeterminate/unknown-duration processes — use Spinner.",
    accessibility: "role=\"progressbar\" with aria-valuenow/min/max.",
    commonMistakes: "Using a Progress Bar for a process with no real measurable progress.",
    tokensUsed: ["semantic/border/default", "semantic/action/primary", "semantic/feedback/success"],
    properties: "Style as variants, shown at a fixed demo fill percentage.",
    knownLimitation: "No numeric \"value\" property exists — Figma doesn't support a float type.",
  },
  {
    slug: "spinner",
    name: "Spinner",
    category: "Feedback",
    variants: "Size (Small/Medium/Large) — 3 variants",
    purpose: "Indicating an indeterminate, in-progress loading state with no known completion percentage.",
    whenToUse: "Any load time where percentage-complete truly isn't knowable.",
    whenNotToUse: "When percentage IS knowable — use Progress Bar.",
    accessibility: "role=\"status\" and an aria-label like \"Loading\" — the spinning animation itself conveys nothing to non-visual users.",
    commonMistakes: "Providing a purely decorative spinner with no accessible label.",
    tokensUsed: ["semantic/border/default", "semantic/action/primary"],
    properties: "Size as variants. Built using a real partial-arc ellipse (Figma's arcData), not a fake icon.",
  },
  {
    slug: "tooltip",
    name: "Tooltip",
    category: "Feedback",
    variants: "Position (Top/Bottom/Left/Right) — 4 variants",
    purpose: "A small floating label providing brief supplementary context for an element, shown on hover or focus.",
    whenToUse: "Clarifying an icon-only control's purpose.",
    whenNotToUse: "Content essential to completing a task. Richer content with multiple pieces of information — use Popover.",
    accessibility: "Must appear on keyboard focus, not just mouse hover; use aria-describedby.",
    commonMistakes: "Implementing hover-only triggering with no keyboard-focus equivalent.",
    tokensUsed: ["color/neutral/900"],
    properties: "Position as variants, each with a correctly oriented arrow pointer. Label (text).",
    knownLimitation: "The arrow's position is a fixed coordinate calculated from placeholder text width — not dynamically bound to Label length.",
  },
  {
    slug: "skeleton",
    name: "Skeleton",
    category: "Feedback",
    variants: "Shape (Text/Circle/Rectangle) — 3 variants",
    purpose: "A placeholder shape mimicking the layout of content that hasn't loaded yet, reducing perceived load time and layout shift.",
    whenToUse: "Any content area with a known layout shape whose real content takes a moment to load.",
    whenNotToUse: "Content with a genuinely unpredictable final shape/size.",
    accessibility: "aria-busy=\"true\" on the container while loading; skeleton shapes themselves aria-hidden.",
    commonMistakes: "Using a skeleton whose shape doesn't reasonably match the real content's eventual layout.",
    tokensUsed: ["color/neutral/300"],
    properties: "Shape as variants — composed together in a real \"Skeleton List Item\" example.",
  },
];
