import { ComponentDoc } from "@/lib/types";

export const formsComponents: ComponentDoc[] = [
  {
    slug: "text-input",
    name: "Text Input",
    category: "Forms",
    variants: "State × Size — 15 variants",
    purpose: "Single-line text entry for short, free-form data (names, emails, search terms, general form fields).",
    whenToUse: "Any single-line free-text field. Pair with FormField for the label/helper/error pattern rather than building that structure per-instance.",
    whenNotToUse: "Multi-line content (use Textarea). A fixed set of choices (use Select). Search-specific fields (use Search Field).",
    accessibility: "Must have a visible or aria-labelled <label> in code — never rely on placeholder text alone. Error state needs aria-invalid and aria-describedby. Focused state uses semantic/focus-ring at 2px outside-aligned stroke.",
    commonMistakes: "Using placeholder text as a substitute for a real label. Not visually distinguishing Disabled from Default strongly enough.",
    tokensUsed: ["component/radius/control", "semantic/border/default", "semantic/border/strong", "semantic/focus-ring", "semantic/action/danger", "semantic/surface/default"],
    properties: "State × Size as variants. Value (text). Show leading/trailing icon (booleans) + Leading/Trailing Icon (instance-swap).",
  },
  {
    slug: "textarea",
    name: "Textarea",
    category: "Forms",
    variants: "State × Size — 15 variants",
    purpose: "Multi-line free-text entry for longer content (descriptions, comments, messages).",
    whenToUse: "Any field expecting more than one line of input.",
    whenNotToUse: "Single-line fields — use Text Input.",
    accessibility: "Same labelling requirements as Text Input. Text wraps and top-aligns rather than vertically centering.",
    commonMistakes: "Using a fixed height too small for realistic content.",
    tokensUsed: ["component/radius/control", "semantic/border/default", "semantic/focus-ring", "semantic/surface/default"],
    properties: "State × Size as variants. Value (text).",
    knownLimitation: "No numeric properties exist for height — real usage may need per-instance manual height adjustment.",
  },
  {
    slug: "checkbox",
    name: "Checkbox",
    category: "Forms",
    variants: "Value (Unchecked/Checked/Indeterminate) × State — 12 variants",
    purpose: "Binary or tri-state selection within a group of independent options (not mutually exclusive).",
    whenToUse: "\"Select any that apply\" scenarios, agreement/consent checkboxes, or a single standalone toggle.",
    whenNotToUse: "Mutually exclusive single-choice (use Radio). A setting that takes effect immediately (use Switch).",
    accessibility: "Renders as a real <input type=\"checkbox\"> with the label programmatically associated. Indeterminate must be set via the DOM property.",
    commonMistakes: "Building the label as a separate, unassociated text element next to the box.",
    tokensUsed: ["semantic/surface/default", "semantic/border/default", "semantic/action/primary", "semantic/focus-ring"],
    properties: "Value × State as variants. Label (text).",
  },
  {
    slug: "radio",
    name: "Radio",
    category: "Forms",
    variants: "Value (Unselected/Selected) × State — 8 variants",
    purpose: "Single selection from a set of mutually exclusive options, all visible at once.",
    whenToUse: "2–6 mutually exclusive options where seeing all choices simultaneously helps the decision.",
    whenNotToUse: "More than ~6 options (use Select). Multiple selections allowed (use Checkbox).",
    accessibility: "All Radios in one group must share the same name attribute and be wrapped in a fieldset/legend or role=\"radiogroup\".",
    commonMistakes: "Forgetting the shared group label/legend.",
    tokensUsed: ["semantic/surface/default", "semantic/border/default", "semantic/action/primary", "semantic/focus-ring"],
    properties: "Value × State as variants. Label (text).",
  },
  {
    slug: "switch",
    name: "Switch",
    category: "Forms",
    variants: "Value (Off/On) × State — 8 variants",
    purpose: "Toggle a setting on/off with immediate effect (no separate form submit required).",
    whenToUse: "Settings that apply instantly when toggled (notifications, dark mode, feature flags).",
    whenNotToUse: "A choice that only takes effect after a form submission (use Checkbox).",
    accessibility: "Renders as role=\"switch\" with aria-checked, not a plain checkbox.",
    commonMistakes: "Using Switch for a setting that actually requires a form submit to take effect.",
    tokensUsed: ["semantic/border/strong", "semantic/action/primary", "semantic/surface/default", "semantic/focus-ring"],
    properties: "Value × State as variants. Label (text). Thumb position driven by the track's alignment property, not hardcoded coordinates.",
  },
  {
    slug: "select",
    name: "Select",
    category: "Forms",
    variants: "State × Size — 15 variants",
    purpose: "Choosing one option from a list too long to show all at once, hidden behind a dropdown trigger.",
    whenToUse: "More than ~6 options, or when vertical space is limited.",
    whenNotToUse: "Fewer than ~6 options (use Radio). A field that also needs free-text search/filter (use Combobox).",
    accessibility: "Renders as a real <select> or a fully custom listbox with role=\"listbox\"/role=\"option\" and complete keyboard support.",
    commonMistakes: "Building a custom-styled dropdown without replicating native <select> keyboard behavior.",
    tokensUsed: ["component/radius/control", "semantic/border/default", "semantic/icon/muted"],
    properties: "State × Size as variants. Value (text, the currently selected option's display text).",
  },
  {
    slug: "validation-message",
    name: "Validation Message",
    category: "Forms",
    variants: "Type (Error/Warning/Success/Info) — 4 variants",
    purpose: "Inline feedback text paired with a form field, communicating error, warning, success, or informational status.",
    whenToUse: "Directly below or near a Form Field Wrapper to explain a field's Error state, or to confirm successful validation.",
    whenNotToUse: "Page-level or app-level notifications unrelated to a specific field (use Alert or Toast instead).",
    accessibility: "Must be programmatically associated with its field via aria-describedby, not just visually placed nearby.",
    commonMistakes: "Relying on icon/color alone to convey meaning without real explanatory text.",
    tokensUsed: [
      "component/validation-message/error/text",
      "component/validation-message/warning/text",
      "component/validation-message/success/text",
      "component/validation-message/info/text",
      "component/validation-message/text",
      "semantic/feedback/warning",
      "semantic/feedback/success",
      "semantic/feedback/info",
    ],
    properties: "Type as variants. Message (text).",
    knownLimitation: "Info type currently reuses the WarningCircle icon — Icon/Info now exists and should be swapped in.",
  },
  {
    slug: "form-field",
    name: "Form Field",
    category: "Forms",
    variants: "State (Default/Error) — composition wrapper",
    purpose: "Shared field chrome for label, description, required indicator, and validation output — wrapping any form control without duplicating field logic per control.",
    whenToUse: "Any control that needs a field label plus helper or error text above/below the control, such as Text Input, Select, or grouped Checkbox lists.",
    whenNotToUse: "Standalone Checkbox, Radio, or Switch instances that already include an inline label. Do not treat Form Field as a visual input.",
    accessibility: "Associates label text with the nested control through htmlFor/id or fieldset/legend patterns. Validation messages must be linked with aria-describedby.",
    commonMistakes: "Embedding label and error logic inside every control instead of composing FormField. Using Form Field as if it were a text input.",
    tokensUsed: ["semantic/text/primary", "semantic/text/secondary", "semantic/text/danger"],
    properties: "Label (text). Required (boolean). Helper Text (text). Control supplied as child render function.",
  },
  {
    slug: "radio-group",
    name: "Radio Group",
    category: "Forms",
    variants: "Group label + options — single selection",
    purpose: "Manages mutually exclusive radio options under one accessible group label with shared name, description, and error relationships.",
    whenToUse: "When 2–6 options should remain visible together and only one may be selected.",
    whenNotToUse: "More than ~6 options (use Select). Multiple independent selections (use Checkbox).",
    accessibility: "Uses fieldset and legend for the group label. Each option is a native radio input sharing the same name. Arrow keys follow native radio group behavior within the set.",
    commonMistakes: "Forgetting a group label/legend. Giving each radio a different name attribute.",
    tokensUsed: ["semantic/surface/default", "semantic/border/default", "semantic/action/primary", "semantic/focus-ring", "semantic/action/danger", "semantic/text/danger"],
    properties: "Group label (text). Options (value + label). Required, disabled, helper, and error supported at group level.",
  },
  {
    slug: "search-field",
    name: "Search Field",
    category: "Forms",
    variants: "State × Size — 12 variants",
    purpose: "A text input specialized for search — always includes a leading search icon and an optional clear button once text is entered.",
    whenToUse: "Any search/filter input, whether inline in a toolbar or as a page-level search bar.",
    whenNotToUse: "General free-text entry unrelated to searching/filtering — use Text Input.",
    accessibility: "The clear button needs an aria-label of \"Clear search\" or equivalent, since it's icon-only.",
    commonMistakes: "Leaving the clear button visible when the field is empty.",
    tokensUsed: ["component/radius/control", "semantic/border/default", "semantic/icon/muted"],
    properties: "State × Size as variants. Value (text). Show clear icon (boolean).",
  },
  {
    slug: "slider",
    name: "Slider",
    category: "Forms",
    variants: "State (Default/Hover/Focused/Disabled) — 4 variants",
    purpose:
      "Slider is a single-value control for selecting a numeric value within a defined min/max by dragging a thumb along a track or adjusting with the keyboard.",
    whenToUse:
      "A value with a naturally continuous or steppable range where dragging is more intuitive than typing (volume, brightness, intensity).",
    whenNotToUse:
      "When precise exact-number entry matters more than approximate visual positioning — use Text Input, or pair both.",
    accessibility:
      "Renders as role=\"slider\" with aria-valuenow/min/max and a visible label. Supports arrow keys, Home/End, and Page Up/Down — not drag alone.",
    commonMistakes: "Implementing drag-only interaction with no keyboard support.",
    tokensUsed: [
      "semantic/border/default",
      "semantic/action/primary",
      "semantic/action/primary-hover",
      "semantic/surface/default",
      "semantic/focus-ring",
      "opacity/disabled",
    ],
    properties:
      "State as interactive variants (Default/Hover/Focused/Disabled). Runtime value/min/max/step are React props — Figma has no numeric value property.",
    knownLimitation:
      "Beta is horizontal single-thumb only. Dual-thumb range and vertical orientation are not in the verified Figma set. Older Style (Success/Warning/Danger) docs text does not match the live component set.",
  },
  {
    slug: "combobox",
    name: "Combobox",
    category: "Forms",
    variants: "State × Size — 15 variants (Figma); Beta React supports default, error, and disabled",
    purpose:
      "An editable single-select field that filters a predefined option list while typing — distinct from non-searchable Select and query-only Search Field.",
    whenToUse:
      "Long predefined option lists where typing to filter is faster than scrolling, such as countries, assignees, or project names.",
    whenNotToUse:
      "Short fixed lists with no search benefit — use Select. Free-text queries without option commitment — use Search Field.",
    accessibility:
      "Uses the editable combobox pattern: native text input with role=\"combobox\", aria-autocomplete=\"list\", aria-controls pointing to a listbox, aria-activedescendant for keyboard navigation while DOM focus stays in the input. Filter status uses a polite role=\"status\" region — not role=\"option\" for empty rows.",
    commonMistakes:
      "Treating typed text as the submitted form value, moving DOM focus into options, or using role=\"dialog\" on the popup shell.",
    tokensUsed: [
      "component/radius/control",
      "combobox/popup-surface",
      "component/menu/item-hover",
      "combobox/option-active-surface",
      "combobox/option-selected-surface",
      "semantic/focus-ring",
    ],
    properties:
      "State as variants. Value stores the committed option value; input text is editable for filtering. Multi-select chips exist in Figma but are deferred in Beta.",
    knownLimitation:
      "Beta supports local prefix/substring filtering only — no remote search, multi-select, clear button, or free-form custom values. Unmatched blur text reverts to the last committed option label.",
  },
  {
    slug: "date-picker",
    name: "Date Picker",
    category: "Forms",
    variants: "State × Size — 5 variants",
    purpose: "Text-input-style entry for a calendar date, intended to trigger a calendar popover for visual date selection.",
    whenToUse: "Any date-entry field where a calendar picker aids accuracy over free-typing.",
    whenNotToUse: "When only a rough date/timeframe matters.",
    accessibility: "The calendar icon should trigger the same popover as clicking the input itself; both need to be keyboard operable.",
    commonMistakes: "Assuming this component includes the calendar grid — pair it with Content/Calendar for the full picker.",
    tokensUsed: ["component/radius/control", "semantic/border/default", "semantic/icon/muted"],
    properties: "State × Size as variants. Value (text, formatted date string).",
  },
  {
    slug: "file-upload",
    name: "File Upload",
    category: "Forms",
    variants: "State (Empty/Dragging/Filled/Error/Disabled) — 5 variants",
    purpose: "A dropzone for uploading one or more files, covering the empty/dragging/filled/error/disabled lifecycle states.",
    whenToUse: "Any file attachment or upload flow (avatar upload, document attachment, bulk import).",
    whenNotToUse: "N/A — this is the standard pattern for file upload.",
    accessibility: "The dropzone must remain a real, labeled file input under the hood — drag-and-drop alone excludes keyboard and screen-reader users.",
    commonMistakes: "Building drag-and-drop as the only interaction path, with no accessible fallback.",
    tokensUsed: ["semantic/border/default", "semantic/action/primary", "semantic/text/danger", "semantic/surface/elevated"],
    properties: "State as variants. File Name (text, only meaningful on the Filled variant).",
    knownLimitation:
      "React Beta implemented (2026-07-13) with native multipart submission, drag-and-drop, advisory validation, and selected-file removal. Live Figma MCP verification, progress UI, preview thumbnails, and controlled files remain deferred. See docs/architecture/file-upload-discovery.md.",
  },
  {
    slug: "credit-card-field",
    name: "Credit Card Field",
    category: "Forms",
    variants: "State (Default/Focused/Error/Disabled) — 4 variants",
    purpose:
      "Credit Card Field is a compound UI control for card number, expiry, and CVC in one visually unified shell. It is a visual/input pattern only — not a payment processor, tokenizer, or PCI vault.",
    whenToUse:
      "When documenting or prototyping the joined card-details pattern. For production card capture, prefer a payment provider’s hosted/tokenized fields.",
    whenNotToUse:
      "When using Stripe Elements / Adyen / similar hosted card elements. Do not treat this React control as sufficient for PCI-sensitive production capture.",
    accessibility:
      "fieldset + legend for the group; each segment is a real text input with its own accessible name (number/expiry/CVC). Focus chrome is shell-level (:focus-within). Generic CreditCard icon is decorative (aria-hidden).",
    commonMistakes:
      "Treating this as one text input. Treating display spaces/slash as stored value. Assuming brand detection or payment authorization. Logging or persisting raw card digits.",
    tokensUsed: [
      "component/radius/control",
      "semantic/border/default",
      "semantic/focus-ring",
      "semantic/action/danger",
      "color/neutral/200",
    ],
    properties:
      "Figma: State + Card Number / Expiry / CVC text. React: label, value/defaultValue/onValueChange ({number,expiry,cvc} digit-only), segment labels/placeholders, disabled, readOnly, required, error, supportingText.",
    knownLimitation:
      "Figma demo TEXT may show masked bullets — React does not mask PANs. No brand logos. No Luhn/network validation. /r deferred to CE-3. This component does not claim PCI compliance.",
  },
  {
    slug: "phone-number-field",
    name: "Phone Number Field",
    category: "Forms",
    variants: "State (Default/Focused/Error/Disabled) — 4 variants",
    purpose:
      "Phone Number Field is a compound UI control pairing a country/dial-code selector with a phone number input as two adjacent bordered controls. It is a visual/input pattern only — not SMS verification, carrier lookup, or reachability checks.",
    whenToUse:
      "When documenting or collecting an international phone number where the dialing country matters. Override `countries` with your production country list.",
    whenNotToUse:
      "When you need OTP/SMS verification, number ownership confirmation, or carrier validation — use a dedicated verification service. For a plain national number with no country selector, use Text Input `type=\"tel\"`.",
    accessibility:
      "fieldset + legend for the group; country Select and number input each have their own accessible names. Flag placeholder is decorative (aria-hidden); country identity comes from Select option text (name + dial code). Number input is type=tel with autocomplete=tel.",
    commonMistakes:
      "Treating the flag as the accessible country label. Assuming the default country list is complete. Treating sanitization as phone verification. Using type=number. Logging or persisting entered numbers from the design-system component.",
    tokensUsed: [
      "component/radius/control",
      "semantic/border/default",
      "semantic/focus-ring",
      "semantic/text/danger",
    ],
    properties:
      "Figma: State + Dial Code / Value text. React: label, country/defaultCountry/onCountryChange, value/defaultValue/onValueChange, countries, countryLabel/numberLabel, placeholder, disabled, readOnly, required, error, supportingText.",
    knownLimitation:
      "Flag is a generic two-stripe placeholder, not real national flags. Default country list is illustrative (12). No national formatting engine — digits and common punctuation (+ spaces () . -) are allowed; no E.164 ownership claim. /r deferred to CE-3. Does not send network requests or verify numbers.",
  },
];
