import { ComponentDoc } from "@/lib/types";

export const navigationComponents: ComponentDoc[] = [
  {
    slug: "breadcrumb",
    name: "Breadcrumb",
    category: "Navigation",
    variants: "Composed from Breadcrumb Item states — Default/Hover/Current",
    purpose: "Shows the user's location within a hierarchical structure using an ordered trail of links and a current-page indicator.",
    whenToUse: "Nested views where users may need to move up one or more levels (documentation, settings, product catalogs).",
    whenNotToUse: "Flat navigation, linear step progress (use Stepper), or unrelated cross-section jumps (use Tabs or Top Navigation).",
    accessibility: "Wrap in nav aria-label=\"Breadcrumb\" with an ordered list. Current page uses aria-current=\"page\" and is not a link. Separators are decorative.",
    commonMistakes: "Making the current page a clickable link. Using Breadcrumb as a progress Stepper.",
    tokensUsed: ["semantic/text/secondary", "semantic/text/primary", "semantic/action/primary"],
    properties: "Composed trail of labels and hrefs. Optional Home icon with accessible name.",
  },
  {
    slug: "pagination",
    name: "Pagination",
    category: "Navigation",
    variants: "Composed from Page Item states — Default/Hover/Current/Disabled",
    purpose: "Changes the visible page within a paged collection or result set using numbered controls and Previous/Next boundaries.",
    whenToUse: "Search results, tables, or galleries where users move between discrete pages of content.",
    whenNotToUse: "Infinite scroll or \"Load more\" patterns without discrete page URLs.",
    accessibility: "nav aria-label=\"Pagination\". Current page uses aria-current=\"page\". Previous/Next have explicit labels. Ellipsis is non-interactive.",
    commonMistakes: "Rendering anchors without href values. Using buttons when pages are URL-addressable.",
    tokensUsed: ["semantic/text/primary", "component/menu/item-hover"],
    properties: "Previous, numbered pages, ellipsis, and Next composed from Page Item patterns.",
  },
  {
    slug: "tabs",
    name: "Tabs",
    category: "Navigation",
    variants: "State × Size — 15 variants",
    purpose: "Switching between related views of content within the same context, without a full page navigation.",
    whenToUse: "2-6 closely related content views the user might flip between repeatedly.",
    whenNotToUse: "Unrelated destinations — use Top Navigation or Sidebar instead.",
    accessibility: "Renders as role=\"tablist\"/role=\"tab\"/role=\"tabpanel\" with arrow-key navigation, not just Tab-key focus.",
    commonMistakes: "Using Tabs for what's actually independent navigation between unrelated sections.",
    tokensUsed: ["semantic/text/secondary", "semantic/action/primary", "semantic/focus-ring"],
    properties: "State × Size as variants. Label (text). Underline indicator visibility verified per-variant.",
  },
  {
    slug: "breadcrumb-item",
    name: "Breadcrumb Item",
    category: "Navigation",
    indexing: "noindex",
    variants: "State (Default/Hover/Current) — 3 variants",
    purpose: "Breadcrumb Item is a single link in a breadcrumb trail showing the user's location within a hierarchy.",
    whenToUse: "Composed with Icon/CaretRight separators to show path depth in a nested structure.",
    whenNotToUse: "Flat, non-hierarchical navigation.",
    accessibility: "Wrap in nav aria-label=\"Breadcrumb\"; final crumb gets aria-current=\"page\" and should not be a link.",
    commonMistakes: "Making the last (current-page) crumb a clickable link.",
    tokensUsed: ["semantic/text/secondary", "semantic/text/primary", "semantic/action/primary"],
    properties: "State as variants. Label (text).",
  },
  {
    slug: "page-item",
    name: "Page Item",
    category: "Navigation",
    indexing: "noindex",
    variants: "State (Default/Hover/Current/Disabled) — 4 variants",
    purpose: "Page Item is a single numbered page control within a Pagination trail.",
    whenToUse: "Composed with prev/next Icon Buttons and an ellipsis for paged content.",
    whenNotToUse: "Infinite-scroll or \"Load more\" patterns.",
    accessibility: "Each page number should be a real link/button with aria-label=\"Page N\"; Current gets aria-current=\"page\".",
    commonMistakes: "Making every page number identical in weight/color.",
    tokensUsed: ["semantic/text/secondary", "semantic/action/primary", "semantic/surface/elevated"],
    properties: "State as variants. Label (text).",
  },
  {
    slug: "step-item",
    name: "Step Item",
    category: "Navigation",
    indexing: "noindex",
    variants: "State (Completed/Current/Upcoming) — 3 variants",
    purpose: "Step Item is a single step within a multi-step Stepper, showing progress through a linear process (checkout, onboarding, setup wizard).",
    whenToUse: "Linear, ordered processes where showing overall progress helps the user.",
    whenNotToUse: "Non-linear or optional-order tasks.",
    accessibility: "aria-current=\"step\" on the active step, ideally an aria-label summarizing \"Step 3 of 5.\"",
    commonMistakes: "Allowing users to click ahead to Upcoming steps that require earlier steps first.",
    tokensUsed: ["semantic/action/primary", "semantic/surface/default", "semantic/border/default"],
    properties: "State as variants — structurally verified so only Completed shows a checkmark. Label (text), per-state Number (text).",
    knownLimitation:
      "Implemented in React as the internal state a Stepper Step derives structurally from child order + currentStep (components/ui/Stepper.tsx) — see /components/stepper for the canonical, publicly documented, implemented pattern. This entry remains Figma-facing prose about the underlying Navigation/Step Item component set; node 2024:2944 confirmed via direct Figma MCP inspection (CE-2J, 2026-09-14).",
  },
  {
    slug: "stepper",
    name: "Stepper",
    category: "Navigation",
    variants: "Composed from Step children — state (Completed/Current/Upcoming) derived from position, not a component variant",
    purpose:
      "Stepper shows progress through a fixed, known-length, ordered sequence of named steps (checkout, onboarding, setup wizard) — a compound Stepper + Step API built against the verified Navigation/Step Item component set.",
    whenToUse:
      "Linear, ordered processes where showing overall progress and remaining steps helps the user, and the full set of steps is known up front.",
    whenNotToUse:
      "Non-linear or optional-order tasks — a Stepper implies sequence, which would be misleading otherwise. Peer independent actions (use Button Group). Form-field exclusive choice (use Radio Group). Switching content panels (use Tabs). Open-ended chronological event history (use Timeline).",
    accessibility:
      "Renders as a real ordered list. aria-current=\"step\" on the Current step. Current/Completed/Upcoming are distinguished by more than color alone (checkmark vs. number, bold vs. regular label weight, fill vs. outline). Requires an accessible name via aria-label or aria-labelledby.",
    commonMistakes:
      "Letting users click ahead to Upcoming steps — Stepper never allows this even when onStepClick is provided. Treating Stepper as a form/wizard state owner — it only derives visual state from currentStep and relays clicks; the app owns navigation, routing, and step progression.",
    tokensUsed: [
      "semantic/action/primary",
      "semantic/surface/default",
      "semantic/border/default",
      "semantic/text/primary",
      "component/surface/content-muted",
      "radius/full",
    ],
    properties:
      "React: currentStep (number, zero-based), onStepClick?(index), aria-label / aria-labelledby. Step: children (label) only — no state, description, or orientation prop.",
    knownLimitation:
      "React-first v1 scope, matching the verified Figma contract exactly: fixed horizontal orientation only (no vertical axis exists in Figma), no description/subtitle/metadata/badge/icon slot, no error/disabled/optional/skipped state, no equal-width mode, and no defined behavior for narrow viewports or long (5+) sequences — Figma's own composed example is a fixed-width demo and does not address this. /r distribution deferred to CE-3.",
  },
  {
    slug: "menu",
    name: "Menu",
    category: "Navigation",
    variants: "Placement (bottom default) · Item states (Default/Hover/Disabled/Destructive)",
    purpose:
      "A compact collection of commands or actions opened from a trigger — use for application commands, contextual actions, overflow menus, and item-specific operations.",
    whenToUse:
      "Application commands, contextual actions, overflow actions, view or sorting commands, and item-specific operations that execute immediately.",
    whenNotToUse:
      "Ordinary site navigation, article link lists, form option selection (use Select), tabs, breadcrumbs, sidebar navigation, long content, or complex forms.",
    accessibility:
      "role=\"menu\" on the menu surface with role=\"menuitem\" rows, aria-haspopup=\"menu\" and aria-expanded on the trigger, roving keyboard focus, typeahead search, Escape dismissal, and Tab exits without trapping focus.",
    commonMistakes:
      "Using Menu for primary navigation links, using Menu where Select is needed for form values, or nesting interactive controls inside menu items.",
    tokensUsed: [
      "menu/surface",
      "menu/item-text",
      "menu/item-hover-surface",
      "semantic/focus-ring",
      "semantic/text/danger",
    ],
    properties:
      "Compound API: Menu, MenuTrigger, MenuContent, MenuItem, MenuGroup, MenuLabel, MenuSeparator. MenuItem supports icon, shortcut, destructive styling, disabled state, and onSelect.",
  },
  {
    slug: "menu-item",
    name: "Menu Item",
    category: "Navigation",
    indexing: "noindex",
    variants: "State (Default/Hover/Selected/Disabled) — 4 variants",
    purpose: "Menu Item is a single row within any dropdown, context, or command menu — the shared building block behind Dropdown Menu, Command Menu, and context menus alike.",
    whenToUse: "Any menu list item needing a leading icon, label, and optional trailing keyboard shortcut.",
    whenNotToUse: "A persistent, always-visible navigation item — use Sidebar Nav Item or Top Nav Item.",
    accessibility: "role=\"menuitem\" within a parent role=\"menu\", with full arrow-key navigation.",
    commonMistakes: "Reusing this component's icon slot without recoloring after an instance-swap — the new icon shows its own master's default color until explicitly recolored.",
    tokensUsed: ["semantic/surface/elevated", "semantic/text/primary", "semantic/action/primary", "semantic/icon/muted"],
    properties: "State as variants. Label (text). Show leading icon (boolean) + Leading Icon (instance-swap). Show shortcut (boolean) + Shortcut (text).",
  },
  {
    slug: "dropdown-trigger",
    name: "Dropdown Trigger",
    category: "Navigation",
    indexing: "noindex",
    variants: "State — 4 variants",
    purpose: "Dropdown Trigger is the clickable button that opens a Dropdown Menu — a bordered control showing a label and a chevron.",
    whenToUse: "Any menu that needs an explicit trigger control.",
    whenNotToUse: "When the trigger is better represented by an existing control (e.g. an Icon Button).",
    accessibility: "Needs aria-haspopup=\"menu\" and aria-expanded reflecting open/closed state.",
    commonMistakes: "Forgetting to update aria-expanded when the menu opens/closes.",
    tokensUsed: ["semantic/border/default", "semantic/focus-ring", "semantic/icon/muted"],
    properties: "State as variants. Label (text).",
  },
  {
    slug: "sidebar-nav-item",
    name: "Sidebar Nav Item",
    category: "Navigation",
    indexing: "noindex",
    variants: "State (Default/Hover/Active/Disabled) — 4 variants",
    purpose: "Sidebar Nav Item is a single navigation item within a persistent app Sidebar, with an icon, label, and Active state indicating current location.",
    whenToUse: "Primary app navigation between major sections in a persistent side panel.",
    whenNotToUse: "Transient or contextual menus — use Menu Item.",
    accessibility: "Active item should have aria-current=\"page\", paired with both background change and Bold text — not color alone.",
    commonMistakes: "Making the Active state too subtle to notice at a glance.",
    tokensUsed: ["semantic/surface/elevated", "semantic/action/primary", "semantic/icon/muted"],
    properties: "State as variants. Label (text). Icon (instance-swap).",
  },
  {
    slug: "top-nav-item",
    name: "Top Nav Item",
    category: "Navigation",
    indexing: "noindex",
    variants: "State (Default/Hover/Active/Disabled) — 4 variants",
    purpose: "Top Nav Item is a single navigation link within a horizontal Top Navigation bar.",
    whenToUse: "Primary app/site navigation in a horizontal header bar.",
    whenNotToUse: "Vertical/persistent app navigation with many items — use Sidebar Nav Item.",
    accessibility: "Same aria-current=\"page\" requirement as Sidebar Nav Item for the Active state.",
    commonMistakes: "Relying on color alone for the Active state — pairs action/primary color with Bold weight deliberately.",
    tokensUsed: ["semantic/text/secondary", "semantic/action/primary"],
    properties: "State as variants. Label (text).",
  },
];
