import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { componentRegistry } from "@/lib/component-registry";

const root = process.cwd();
const AGENT_DIR = join(root, "public", "agent");
const CONTRACTS_DIR = join(AGENT_DIR, "contracts");

/**
 * These tests exercise the REAL generated bytes on disk (not the in-memory
 * compiler output already covered by contract-compiler.test.ts) — the
 * actual artifact tree a production deploy would serve at /agent/*. See
 * docs/architecture/agent-kit.md's "AK-3 retrieval architecture" section.
 */

function regenerate(): void {
  execFileSync("npx", ["tsx", "scripts/generate-agent-context.ts"], { cwd: root, stdio: "pipe" });
}

function sha256(content: string): string {
  return createHash("sha256").update(content).digest("hex");
}

describe("retrieval — build emits the full expected artifact tree", () => {
  regenerate();

  it("emits index.json and system.json", () => {
    expect(existsSync(join(AGENT_DIR, "index.json"))).toBe(true);
    expect(existsSync(join(AGENT_DIR, "system.json"))).toBe(true);
  });

  it("emits exactly one contracts/<slug>.json per registry component, no more, no fewer", () => {
    const expectedFiles = componentRegistry.map((entry) => `${entry.slug}.json`).sort();
    const actualFiles = readdirSync(CONTRACTS_DIR).sort();
    expect(actualFiles).toEqual(expectedFiles);
  });

  it("index.json's component list corresponds 1:1 to the generated contract files", () => {
    const index = JSON.parse(readFileSync(join(AGENT_DIR, "index.json"), "utf8")) as {
      components: Array<{ slug: string }>;
    };
    for (const component of index.components) {
      expect(existsSync(join(CONTRACTS_DIR, `${component.slug}.json`))).toBe(true);
    }
  });

  it("a contract file's own slug/name matches the index entry", () => {
    const index = JSON.parse(readFileSync(join(AGENT_DIR, "index.json"), "utf8")) as {
      components: Array<{ slug: string; name: string; status: string }>;
    };
    const sample = index.components[0];
    const contract = JSON.parse(readFileSync(join(CONTRACTS_DIR, `${sample.slug}.json`), "utf8")) as {
      slug: string;
      name: string;
      status: string;
    };
    expect(contract.slug).toBe(sample.slug);
    expect(contract.name).toBe(sample.name);
    expect(contract.status).toBe(sample.status);
  });
});

describe("retrieval — no dynamic route exists (the actual safety boundary)", () => {
  it("has no app/agent route handler — /agent/* is served purely from public/, so an unknown path 404s by construction rather than by application logic", () => {
    // A dynamic [slug]/route.ts would need to defend against path
    // traversal itself. Static public/ file serving needs no such
    // defense — Next.js only ever resolves real, pre-existing files under
    // public/. Proving the route handler doesn't exist IS the proof.
    const candidatePaths = [
      join(root, "app", "agent"),
      join(root, "app", "agent", "[slug]"),
      join(root, "app", "agent", "contracts"),
      join(root, "app", "agent", "contracts", "[slug]"),
    ];
    for (const candidate of candidatePaths) {
      expect(existsSync(candidate)).toBe(false);
    }
  });

  it("an unknown slug has no corresponding file on disk — the same 404 a real request would get", () => {
    expect(existsSync(join(CONTRACTS_DIR, "not-a-real-component.json"))).toBe(false);
  });

  it("a path-traversal-shaped slug has no corresponding literal file — there is nothing on disk for a route to accidentally resolve", () => {
    // Next's public/ static serving treats the request path as a literal
    // file lookup, never as a traversal expression — a request for
    // "..%2f..%2f..%2fpackage.json" looks for a file with that literal
    // name under public/agent/contracts/, which does not exist. Confirmed
    // live against the production server in the AK-3 audit (404).
    expect(existsSync(join(CONTRACTS_DIR, "..%2f..%2f..%2fpackage.json"))).toBe(false);
  });
});

describe("retrieval — public-safety leak guard on the real generated bytes", () => {
  it("no generated file contains an absolute local filesystem path", () => {
    const allFiles = [
      join(AGENT_DIR, "index.json"),
      join(AGENT_DIR, "system.json"),
      ...readdirSync(CONTRACTS_DIR).map((name) => join(CONTRACTS_DIR, name)),
    ];
    for (const filePath of allFiles) {
      const content = readFileSync(filePath, "utf8");
      expect(content, filePath).not.toMatch(/\/Users\//);
      expect(content, filePath).not.toMatch(/\/home\/[a-z]/);
      expect(content, filePath).not.toMatch(/C:\\\\/);
    }
  });

  it("no generated file contains an env-var reference or credential-shaped string", () => {
    const allFiles = [
      join(AGENT_DIR, "index.json"),
      join(AGENT_DIR, "system.json"),
      ...readdirSync(CONTRACTS_DIR).map((name) => join(CONTRACTS_DIR, name)),
    ];
    for (const filePath of allFiles) {
      const content = readFileSync(filePath, "utf8");
      expect(content, filePath).not.toMatch(/\bprocess\.env\b/);
      expect(content, filePath).not.toMatch(/\b(api[_-]?key|secret)\s*[:=]\s*"[A-Za-z0-9]{8,}/i);
    }
  });

  it("provenance is limited to public-safe fields — a git SHA and its own commit timestamp, nothing else", () => {
    const index = JSON.parse(readFileSync(join(AGENT_DIR, "index.json"), "utf8")) as {
      provenance: Record<string, unknown>;
    };
    expect(Object.keys(index.provenance).sort()).toEqual(
      ["generatorVersion", "schemaVersion", "sourceGitCommitTimestamp", "sourceGitSha"].sort(),
    );
    expect(index.provenance.sourceGitSha).toMatch(/^[0-9a-f]{40}$/);
  });
});

describe("retrieval — determinism across a fresh regeneration", () => {
  it("two generations at the same source SHA produce byte-identical public/agent output", () => {
    function collect(): Record<string, string> {
      const files: Record<string, string> = {
        "index.json": readFileSync(join(AGENT_DIR, "index.json"), "utf8"),
        "system.json": readFileSync(join(AGENT_DIR, "system.json"), "utf8"),
      };
      for (const name of readdirSync(CONTRACTS_DIR)) {
        files[`contracts/${name}`] = readFileSync(join(CONTRACTS_DIR, name), "utf8");
      }
      return files;
    }

    const before = collect();

    // Force a clean slate so this proves generation, not a stale no-op.
    rmSync(AGENT_DIR, { recursive: true, force: true });
    regenerate();

    const after = collect();
    const beforeKeys = Object.keys(before).sort();
    const afterKeys = Object.keys(after).sort();
    expect(afterKeys).toEqual(beforeKeys);
    for (const key of afterKeys) {
      expect(sha256(after[key]), key).toBe(sha256(before[key]));
    }
  });
});
