import type { HarnessLine } from "@/lib/ccv/shadcn/exports-harness";

/**
 * CCV-3 — the generated clean Vite + React + TypeScript consumer, the export
 * surface harness and the plain-Node resolution probe. Everything is generated
 * from the CCV-1 contract and the exact pins; nothing names a component.
 */

export const CCV_VITE_CONSUMER_PINS = {
  react: "19.2.7",
  "react-dom": "19.2.7",
  vite: "8.1.4",
  "@vitejs/plugin-react": "6.0.3",
  typescript: "5.9.3",
  "@types/react": "19.2.17",
  "@types/react-dom": "19.2.3",
} as const;

export type VitePins = Record<keyof typeof CCV_VITE_CONSUMER_PINS, string>;

export const SURFACE_HARNESS_PATH = "src/ccv-surface.ts";
export const PROBE_PATH = "ccv-probe.mjs";

export function consumerPackageJson(packageName: string, tarballPath: string, pins: VitePins = CCV_VITE_CONSUMER_PINS): string {
  return `${JSON.stringify(
    {
      name: "skrewww-ccv-npm-consumer",
      private: true,
      version: "0.0.0",
      type: "module",
      dependencies: { react: pins.react, "react-dom": pins["react-dom"], [packageName]: `file:${tarballPath}` },
      devDependencies: {
        vite: pins.vite,
        "@vitejs/plugin-react": pins["@vitejs/plugin-react"],
        typescript: pins.typescript,
        "@types/react": pins["@types/react"],
        "@types/react-dom": pins["@types/react-dom"],
      },
    },
    null,
    2,
  )}\n`;
}

/** Strict, no path mapping, declarations of installed packages checked (`skipLibCheck: false`), as the package smoke does. */
export const CONSUMER_TSCONFIG = `${JSON.stringify(
  {
    compilerOptions: {
      target: "ES2022",
      lib: ["ES2022", "DOM", "DOM.Iterable"],
      module: "ESNext",
      moduleResolution: "bundler",
      jsx: "react-jsx",
      strict: true,
      noEmit: true,
      skipLibCheck: false,
      isolatedModules: true,
      types: ["vite/client"],
    },
    include: ["src"],
  },
  null,
  2,
)}\n`;

export const VITE_CONFIG = 'import react from "@vitejs/plugin-react";\nimport { defineConfig } from "vite";\n\nexport default defineConfig({ plugins: [react()] });\n';

export const INDEX_HTML = '<!doctype html>\n<html lang="en">\n  <head><meta charset="UTF-8" /><title>ccv npm consumer</title></head>\n  <body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>\n</html>\n';

export function mainTsx(stylesheetSpecifier: string): string {
  return [
    `import "${stylesheetSpecifier}";`,
    'import { createRoot } from "react-dom/client";',
    'import { ccvRuntimeExports } from "./ccv-surface";',
    "",
    "function App() {",
    "  return <main data-ccv-exports={ccvRuntimeExports.length} />;",
    "}",
    "",
    'createRoot(document.getElementById("root")!).render(<App />);',
    "",
  ].join("\n");
}

export type SurfaceHarness = { path: string; source: string; lines: Map<number, HarnessLine> };

/** Imports every expected value and type export from the package ROOT, one name per line, so a diagnostic maps to one export. */
export function generateSurfaceHarness(packageName: string, values: readonly string[], types: readonly string[]): SurfaceHarness {
  const out = ["// GENERATED by Skrewww CCV-3 (consumer contract verification)."];
  const lines = new Map<number, HarnessLine>();
  const push = (text: string, line?: HarnessLine) => {
    out.push(text);
    if (line) lines.set(out.length, line);
  };
  if (types.length > 0) {
    push("import type {");
    for (const name of types) push(`  ${name},`, { installPath: packageName, name, kind: "type" });
    push(`} from "${packageName}";`);
  }
  if (values.length > 0) {
    push("import {");
    for (const name of values) push(`  ${name},`, { installPath: packageName, name, kind: "value" });
    push(`} from "${packageName}";`);
  }
  push("");
  push("export const ccvRuntimeExports: readonly unknown[] = [");
  for (const name of values) push(`  ${name},`, { installPath: packageName, name, kind: "value" });
  push("];");
  if (types.length > 0) {
    push("");
    push("// Every type import above must resolve; generic types are imported, not instantiated.");
    push(`export type CcvTypeExportCount = ${types.length};`);
  }
  return { path: SURFACE_HARNESS_PATH, source: `${out.join("\n")}\n`, lines };
}

/**
 * Plain Node ESM probe: imports the package root (runtime export names) and
 * resolves each public and denied specifier with `import.meta.resolve` — CSS is
 * resolved, never imported. Prints one JSON line; resolved targets are reported
 * relative to the installed package.
 */
export function generateProbe(packageName: string, specifiers: readonly string[]): string {
  return [
    "// GENERATED by Skrewww CCV-3 — plain Node ESM probe.",
    `const packageName = ${JSON.stringify(packageName)};`,
    `const specifiers = ${JSON.stringify(specifiers)};`,
    'const marker = `/node_modules/${packageName}/`;',
    "const relativeTarget = (url) => { const index = url.indexOf(marker); return index === -1 ? `outside:${url.split('/').slice(-2).join('/')}` : url.slice(index + marker.length); };",
    "const out = { root: null, resolutions: {} };",
    "try {",
    "  const module = await import(packageName);",
    "  out.root = { ok: true, keys: Object.keys(module).sort() };",
    "} catch (error) {",
    "  out.root = { ok: false, code: error?.code ?? null, message: String(error?.message ?? error).slice(0, 300) };",
    "}",
    "for (const specifier of specifiers) {",
    "  try {",
    "    out.resolutions[specifier] = { resolved: true, target: relativeTarget(import.meta.resolve(specifier)) };",
    "  } catch (error) {",
    "    out.resolutions[specifier] = { resolved: false, code: error?.code ?? null, message: String(error?.message ?? error).slice(0, 200) };",
    "  }",
    "}",
    "process.stdout.write(JSON.stringify(out) + '\\n');",
    "",
  ].join("\n");
}

export type ProbeOutput = {
  root: { ok: true; keys: string[] } | { ok: false; code: string | null; message: string };
  resolutions: Record<string, { resolved: true; target: string } | { resolved: false; code: string | null; message: string }>;
};

export function parseProbeOutput(stdout: string): ProbeOutput | undefined {
  const line = stdout.trim().split(/\r?\n/).reverse().find((candidate) => candidate.startsWith("{"));
  if (!line) return undefined;
  try {
    return JSON.parse(line) as ProbeOutput;
  } catch {
    return undefined;
  }
}

export type SpecifierVerdict = { status: "pass" | "fail" | "unknown"; failureCode?: "DEEP_IMPORT_EXPOSED" | "IMPORT_UNRESOLVED"; detail: string };

/** Public specifiers must resolve inside the installed package; denied ones must be refused by the exports map (`ERR_PACKAGE_PATH_NOT_EXPORTED`). */
export function judgeSpecifier(kind: "public" | "denied", outcome: ProbeOutput["resolutions"][string] | undefined): SpecifierVerdict {
  if (!outcome) return { status: "unknown", detail: "no probe outcome" };
  if (kind === "public") {
    if (outcome.resolved && !outcome.target.startsWith("outside:")) return { status: "pass", detail: `resolves to ${outcome.target} in the installed package` };
    if (outcome.resolved) return { status: "fail", failureCode: "IMPORT_UNRESOLVED", detail: `resolves outside the installed package (${outcome.target})` };
    return { status: "fail", failureCode: "IMPORT_UNRESOLVED", detail: `does not resolve: ${outcome.code ?? "no code"} ${outcome.message}` };
  }
  if (outcome.resolved) return { status: "fail", failureCode: "DEEP_IMPORT_EXPOSED", detail: `resolves to ${outcome.target}` };
  if (outcome.code === "ERR_PACKAGE_PATH_NOT_EXPORTED") return { status: "pass", detail: "refused by the exports map (ERR_PACKAGE_PATH_NOT_EXPORTED)" };
  return { status: "unknown", detail: `refused for another reason, so exports-map denial is not proven: ${outcome.code ?? "no code"} ${outcome.message}` };
}

export function compareRuntimeExports(actual: readonly string[], expected: readonly string[]): { missing: string[]; unexpected: string[] } {
  return { missing: expected.filter((name) => !actual.includes(name)), unexpected: actual.filter((name) => !expected.includes(name)).sort() };
}
