/**
 * CCV-2 — a generated consumer-side module that imports every export CCV-1
 * attributes to each installed source file, FROM that installed file through
 * the consumer's `@/` alias (no invented root barrel). Values are imported and
 * referenced at runtime; types are imported with `import type`. Each name sits on
 * its own line so a TypeScript diagnostic maps back to exactly one export.
 */

export const EXPORTS_HARNESS_PATH = "ccv/exports-harness.tsx";

export type HarnessLine = { installPath: string; name: string; kind: "value" | "type" };

export type ExportsHarness = { path: string; source: string; lines: Map<number, HarnessLine> };

export function moduleSpecifierFor(installPath: string): string {
  return `@/${installPath.replace(/\.(tsx?|jsx?)$/, "")}`;
}

export function generateExportsHarness(entries: ReadonlyArray<{ installPath: string; values: readonly string[]; types: readonly string[] }>): ExportsHarness {
  const out: string[] = ['"use client";', "// GENERATED by Skrewww CCV-2 (consumer contract verification). Not part of the installed result."];
  const lines = new Map<number, HarnessLine>();
  const valueRefs: Array<{ alias: string; line: HarnessLine }> = [];
  const push = (text: string, line?: HarnessLine) => {
    out.push(text);
    if (line) lines.set(out.length, line);
  };
  entries.forEach((entry, index) => {
    const specifier = moduleSpecifierFor(entry.installPath);
    if (entry.values.length > 0) {
      push("import {");
      for (const name of entry.values) {
        const alias = `v${index}_${name}`;
        const line: HarnessLine = { installPath: entry.installPath, name, kind: "value" };
        push(`  ${name} as ${alias},`, line);
        valueRefs.push({ alias, line });
      }
      push(`} from "${specifier}";`);
    }
    if (entry.types.length > 0) {
      push("import type {");
      for (const name of entry.types) push(`  ${name} as t${index}_${name},`, { installPath: entry.installPath, name, kind: "type" });
      push(`} from "${specifier}";`);
    }
  });
  push("");
  push("export default function CcvExportsHarness(): null {");
  push("  void [");
  for (const ref of valueRefs) push(`    ${ref.alias},`, ref.line);
  push("  ];");
  push("  return null;");
  push("}");
  return { path: EXPORTS_HARNESS_PATH, source: `${out.join("\n")}\n`, lines };
}

export const CONSUMER_PAGE_PATH = "app/page.tsx";

/** The page that makes the production build compile every installed module (no rendering assertions — CCV-4 owns runtime). */
export function generateConsumerPage(foundationInstallPath: string | undefined): string {
  return [
    foundationInstallPath ? `import "@/${foundationInstallPath}";` : "",
    'import CcvExportsHarness from "@/ccv/exports-harness";',
    "",
    "export default function Page() {",
    "  return (",
    "    <main>",
    "      <CcvExportsHarness />",
    "    </main>",
    "  );",
    "}",
    "",
  ].filter((line, index) => line !== "" || index > 0).join("\n");
}
