/**
 * Writes the shadcn-compatible distribution manifests to public/r/.
 *
 * All actual generation logic lives in lib/shadcn-registry-generator.ts.
 * Run via `npm run generate:registry` (also part of `npm run build`).
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  buildButtonManifest,
  buildCardManifest,
  buildCheckboxManifest,
  buildDividerManifest,
  buildFormFieldManifest,
  buildFoundationManifest,
  buildLinkManifest,
  buildPaginationManifest,
  buildProgressBarManifest,
  buildRadioManifest,
  buildRadioGroupManifest,
  buildAvatarManifest,
  buildBreadcrumbManifest,
  buildSkeletonManifest,
  buildSpinnerManifest,
  buildSwitchManifest,
  buildSliderManifest,
  buildStepperManifest,
  buildTableManifest,
  buildTextareaManifest,
  buildTextInputManifest,
  buildValidationMessageManifest,
  buildBadgeManifest,
  buildTagManifest,
  buildListItemManifest,
  buildTimelineManifest,
  buildEmptyStateManifest,
  buildAlertManifest,
  buildToastManifest,
  buildButtonGroupManifest,
  buildToggleGroupManifest,
  buildAccordionManifest,
  buildTabsManifest,
  buildSearchFieldManifest,
  buildCreditCardFieldManifest,
  buildNumberInputManifest,
  buildFileUploadManifest,
  buildPopoverManifest,
  buildTooltipManifest,
  buildDialogManifest,
  buildDrawerManifest,
  buildMenuManifest,
  buildSplitButtonManifest,
  buildComboboxManifest,
  buildSelectManifest,
  buildCalendarDayManifest,
  buildCalendarGridManifest,
  buildDatePickerManifest,
  buildPhoneNumberFieldManifest,
  buildTreeViewManifest,
  buildDataTableManifest,
  buildBarChartManifest,
  buildLineChartManifest,
} from "../lib/shadcn-registry-generator";

const OUT_DIR = join(process.cwd(), "public", "r");

mkdirSync(OUT_DIR, { recursive: true });

const manifests = [
  ["foundation.json", buildFoundationManifest()],
  ["button.json", buildButtonManifest()],
  ["card.json", buildCardManifest()],
  ["text-input.json", buildTextInputManifest()],
  ["form-field.json", buildFormFieldManifest()],
  ["validation-message.json", buildValidationMessageManifest()],
  ["spinner.json", buildSpinnerManifest()],
  ["divider.json", buildDividerManifest()],
  ["link.json", buildLinkManifest()],
  ["checkbox.json", buildCheckboxManifest()],
  ["progress-bar.json", buildProgressBarManifest()],
  ["skeleton.json", buildSkeletonManifest()],
  ["radio.json", buildRadioManifest()],
  ["switch.json", buildSwitchManifest()],
  ["textarea.json", buildTextareaManifest()],
  ["pagination.json", buildPaginationManifest()],
  ["avatar.json", buildAvatarManifest()],
  ["breadcrumb.json", buildBreadcrumbManifest()],
  ["radio-group.json", buildRadioGroupManifest()],
  ["slider.json", buildSliderManifest()],
  ["stepper.json", buildStepperManifest()],
  ["table.json", buildTableManifest()],
  ["badge.json", buildBadgeManifest()],
  ["tag.json", buildTagManifest()],
  ["list-item.json", buildListItemManifest()],
  ["timeline.json", buildTimelineManifest()],
  ["empty-state.json", buildEmptyStateManifest()],
  ["alert.json", buildAlertManifest()],
  ["toast.json", buildToastManifest()],
  ["button-group.json", buildButtonGroupManifest()],
  ["toggle-group.json", buildToggleGroupManifest()],
  ["accordion.json", buildAccordionManifest()],
  ["tabs.json", buildTabsManifest()],
  ["search-field.json", buildSearchFieldManifest()],
  ["credit-card-field.json", buildCreditCardFieldManifest()],
  ["number-input.json", buildNumberInputManifest()],
  ["file-upload.json", buildFileUploadManifest()],
  ["popover.json", buildPopoverManifest()],
  ["tooltip.json", buildTooltipManifest()],
  ["dialog.json", buildDialogManifest()],
  ["drawer.json", buildDrawerManifest()],
  ["menu.json", buildMenuManifest()],
  ["split-button.json", buildSplitButtonManifest()],
  ["calendar-day.json", buildCalendarDayManifest()],
  ["calendar-grid.json", buildCalendarGridManifest()],
  ["select.json", buildSelectManifest()],
  ["combobox.json", buildComboboxManifest()],
  ["date-picker.json", buildDatePickerManifest()],
  ["phone-number-field.json", buildPhoneNumberFieldManifest()],
  ["tree-view.json", buildTreeViewManifest()],
  ["data-table.json", buildDataTableManifest()],
  ["bar-chart.json", buildBarChartManifest()],
  ["line-chart.json", buildLineChartManifest()],
] as const;

console.log("Generated shadcn registry manifests:");
for (const [filename, manifest] of manifests) {
  const path = join(OUT_DIR, filename);
  writeFileSync(path, `${JSON.stringify(manifest, null, 2)}\n`);
  console.log(" -", path);
}
