/**
 * Canonical-source driven entry for the `@skrewww/react` package candidate.
 *
 * The package is a distribution boundary, not a second component library: its
 * entry file is generated at build time from
 *   - the canonical registry (which slugs are in the pilot, and that each one
 *     exists and is implemented), and
 *   - the canonical public barrel `components/ui/index.ts` (which names each
 *     component module exports),
 * so nothing here duplicates a component implementation, an export list or a
 * maturity status.
 */
import type { ComponentRegistryEntry } from "@/lib/component-registry";

/** MK-1 pilot surface, by registry slug. Charts and Beta components are deliberately absent. */
export const REACT_PACKAGE_PILOT_SLUGS = [
  "button",
  "link",
  "card",
  "text-input",
  "form-field",
  "validation-message",
  "spinner",
  "dialog",
] as const;

/** The optional router integration module that ships with the pilot (not a registry component). */
export const REACT_PACKAGE_ROUTER_MODULE = "router-navigation";

export type PilotComponentFact = {
  slug: string;
  status: ComponentRegistryEntry["status"];
  module: string;
};

const TOP_LEVEL_COMPONENT_FILE = /^components\/ui\/([A-Za-z0-9]+)\.tsx$/;

/** Resolves pilot slugs to their canonical component modules; throws if one is missing or unimplemented. */
export function resolvePilotComponents(
  registry: readonly ComponentRegistryEntry[],
  slugs: readonly string[] = REACT_PACKAGE_PILOT_SLUGS,
): PilotComponentFact[] {
  return slugs.map((slug) => {
    const entry = registry.find((candidate) => candidate.slug === slug);
    if (!entry) throw new Error(`Pilot slug "${slug}" is not in the canonical registry.`);
    if (!entry.hasImplementation) throw new Error(`Pilot slug "${slug}" has no React implementation.`);
    const source = (entry.files ?? []).map((file) => TOP_LEVEL_COMPONENT_FILE.exec(file)).find(Boolean);
    if (!source) throw new Error(`Pilot slug "${slug}" has no top-level components/ui/<Name>.tsx file.`);
    return { slug, status: entry.status, module: source[1] };
  });
}

const BARREL_EXPORT_STATEMENT = /export\s+(?:type\s+)?\{[^}]*\}\s+from\s+"@\/components\/ui\/([^"]+)";?/g;

/**
 * Selects, verbatim, the barrel's export statements for the given modules.
 * Every requested module must appear in the barrel as a value export — an
 * internal-only module can never leak into the package this way.
 */
export function selectBarrelExports(barrelSource: string, modules: readonly string[]): string {
  const wanted = new Set(modules);
  const statements: string[] = [];
  const valueExportsFound = new Set<string>();
  for (const match of Array.from(barrelSource.matchAll(BARREL_EXPORT_STATEMENT))) {
    const statement = match[0];
    const moduleName = match[1];
    if (!wanted.has(moduleName)) continue;
    statements.push(statement.endsWith(";") ? statement : `${statement};`);
    if (!/^export\s+type\s/.test(statement)) valueExportsFound.add(moduleName);
  }
  const missing = modules.filter((name) => !valueExportsFound.has(name));
  if (missing.length > 0) {
    throw new Error(`Public barrel components/ui/index.ts does not export: ${missing.join(", ")}`);
  }
  return statements.join("\n");
}

export type ModuleExports = { values: string[]; types: string[] };

/**
 * Public export names per barrel module, in barrel order, split into runtime
 * values and type-only exports. Reads the same barrel statements the package
 * entry re-exports, so it is the actual public surface, never a second list.
 */
export function readBarrelExportsByModule(
  barrelSource: string,
  modules: readonly string[],
): Record<string, ModuleExports> {
  const wanted = new Set(modules);
  const result: Record<string, ModuleExports> = {};
  for (const match of Array.from(barrelSource.matchAll(BARREL_EXPORT_STATEMENT))) {
    const moduleName = match[1];
    if (!wanted.has(moduleName)) continue;
    const isType = /^export\s+type\s/.test(match[0]);
    const names = (/\{([^}]*)\}/.exec(match[0])?.[1] ?? "")
      .split(",")
      .map((part) => part.trim().split(/\s+as\s+/).pop()?.trim() ?? "")
      .filter(Boolean);
    const entry = (result[moduleName] ??= { values: [], types: [] });
    (isType ? entry.types : entry.values).push(...names);
  }
  return result;
}

export function buildReactPackageEntry(
  registry: readonly ComponentRegistryEntry[],
  barrelSource: string,
): { source: string; components: PilotComponentFact[]; exportsByModule: Record<string, ModuleExports> } {
  const components = resolvePilotComponents(registry);
  const modules = [...components.map((component) => component.module), REACT_PACKAGE_ROUTER_MODULE];
  const source = [
    "// GENERATED by scripts/build-react-package.ts from the canonical registry and",
    "// components/ui/index.ts. Do not edit; not committed.",
    selectBarrelExports(barrelSource, modules),
    "",
  ].join("\n");
  return { source, components, exportsByModule: readBarrelExportsByModule(barrelSource, modules) };
}
